services:
  bit-bot:
    image: utdmakerspace/bit-bot
    build: . 
    restart: "unless-stopped"
    volumes:
      - ./data/node-persist:/opt/bitbot/.node-persist
    env_file:
      - path: ./.env
        required: true
    depends_on:
      - db
  db:
    image: mongo:5.0
    restart: "unless-stopped"
    env_file:
      - path: .env.db
        required: true
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'
